fix: use symbol as a key for the "others" handler
the-dr-lazy/deox pull request #159
Opened 2020-10-03 15:52 UTC by Jazzmanpw

I believe the work is mostly finished. I only have one typing issue, but I'm not sure if it's a problem.
When I run dts tests, [one for createReducer](https://github.com/the-dr-lazy/deox/blob/9c93e3842fc8d9cdab264440be000b20bc990e31/src/__tests__/create-reducer.dts.spec.ts#L76) falis (it worked previously, but some other types were not correct). In [this](https://github.com/the-dr-lazy/deox/blob/9c93e3842fc8d9cdab264440be000b20bc990e31/src/__tests__/__snapshots__/create-reducer.dts.spec.ts.snap#L5) line it determines the action type as `any`.

I don't know if there's any use of an exact action type for a reducer and assume that such behavior shouldn't be dangerous. As well as it affects only the new `handle.others` feature, so it's back compatible.

My question is: is it OK to have the `any` type there, or should I try and find some way for a better structure for type inferring?

2020-10-03 15:57 UTC, Jazzmanpw commented
And maybe I need to create a new fork just for the last commits, don't I?

2020-10-04 21:13 UTC, the-dr-lazy requested changes

2020-10-04 21:13 UTC, the-dr-lazy commented on src/create-reducer.ts
> +    const othersHandler = handlerMap[othersHandlerKey]
This can be reduce to:

```ts
const handler = handlerMap[(<any>action).type] || handlerMap[othersHandlerKey]
```

2020-10-04 21:14 UTC, the-dr-lazy commented
> And maybe I need to create a new fork just for the last commits, don't I?

Maybe pull the latest master or next branch.

2020-10-06 13:30 UTC, Jazzmanpw commented
I believe I screwed up this pull request a little bit. I found how to pull the changes from the original repo, but they're now all in this pull request. I've added a couple of commits before the pull and one that you've requested. Is it convenient to merge these changes? The `Files changes` tab looks a little bit messy

2020-10-06 13:30 UTC, Jazzmanpw commented
The original question about `any` is still actual.

2020-10-09 13:29 UTC, the-dr-lazy commented
> is it OK to have the any type there, or should I try and find some way for a better structure for type inferring?

It's important to have correct type for created reducer.

2020-10-09 14:09 UTC, the-dr-lazy commented
> You should pull the upstream with rebase.

I fixed the branching problem. Sorry, but I should force push to fix it.

2020-10-09 15:03 UTC, the-dr-lazy commented
Please let me know your opinion about the changes I have made.

2020-10-09 15:04 UTC, the-dr-lazy approved these changes

2020-10-17 04:48 UTC, the-dr-lazy commented
I think this PR is ready to merge and release. Hope you think so @Jazzmanpw.

2020-10-17 04:49 UTC, merged

2020-10-17 12:44 UTC, Jazzmanpw commented
I'm sorry for being away for so long.
Thank you for the changes. I still don't feel comfortable with TS. And I'm not sure if I could do it better. As well as I don't see any remaining bugs.

2020-10-17 15:19 UTC, the-dr-lazy commented
Thank you for your contribution @Jazzmanpw.
If you are interested in type-level programming in statically typed languages such as TS which inspired their type system from ML languages especially Haskell, I suggest you learning Haskell. It's the best teacher I ever had.

2020-10-17 21:03 UTC, Jazzmanpw commented
Thank you for the advice. And for the opportunity to become a part of the open-source community. =)